from langchain_ollama import ChatOllama
from .schema import get_database_schema
import re


class SQLGenerator:

    def __init__(self):
        self.llm = ChatOllama(
            model="qwen2.5:3b",
            temperature=0
        )

    def generate_sql(self, question):

        schema = get_database_schema()

        prompt = f"""
You are a SQL expert working with Microsoft SQL Server.

Convert the user's business question into ONE valid SQL SELECT query.

Use ONLY the tables and columns provided in the schema.

Do not invent tables or columns.

Database schema:
{schema}

User question:
{question}

Rules:
- Return ONLY the SQL query.
- Do not use markdown code fences.
- Use Microsoft SQL Server syntax.
- Use sales_amount when calculating revenue.
- Do not JOIN tables unless the question requires data from multiple tables.
- The region column for sales analysis is Sales.region.
- When using columns from joined tables, always qualify them with the table name.
- NEVER use LIMIT.
- For a single-row result, use TOP 1 instead of LIMIT 1.
- Use TOP only immediately after SELECT, for example: SELECT TOP 1 ...
- NEVER put TOP inside SUM(), AVG(), COUNT(), or any other aggregate function.
- For "total revenue by region", return every region and do not use TOP.
- Use SUM(sales_amount) for revenue calculations.
- Return only valid Microsoft SQL Server SELECT SQL.
"""


        response = self.llm.invoke(prompt)

        sql_query = response.content.strip()
        print("SQL GENERATED BY LLM:", repr(sql_query))

                # Protect total-revenue questions from accidental grouping.
        question_lower = question.lower()

        is_total_revenue = (
            "total sales revenue" in question_lower
            or "total revenue" in question_lower
        )

        has_grouping_intent = " by " in question_lower

        if is_total_revenue and not has_grouping_intent:
            sql_query = re.sub(
                r"\s+GROUP\s+BY\s+[\w.]+(?:\s*,\s*[\w.]+)*",
                "",
                sql_query,
                flags=re.IGNORECASE
            ).strip()
        # Remove accidental markdown fences if the model adds them
        if sql_query.startswith("```"):
            sql_query = sql_query.replace("```sql", "")
            sql_query = sql_query.replace("```", "")
            sql_query = sql_query.strip()

        fetch_match = re.search(
            r"\bFETCH\s+FIRST\s+(\d+)\s+ROWS?\s+ONLY\b",
            sql_query,
            re.IGNORECASE
        )

        if fetch_match:
            limit_value = fetch_match.group(1)

            sql_query = re.sub(
                r"\bFETCH\s+FIRST\s+\d+\s+ROWS?\s+ONLY\b",
                "",
                sql_query,
                flags=re.IGNORECASE
            ).strip()

            sql_query = re.sub(
                r"^\s*SELECT\s+",
                f"SELECT TOP {limit_value} ",
                sql_query,
                count=1,
                flags=re.IGNORECASE
            )
        # Convert LIMIT n OFFSET m to SQL Server OFFSET/FETCH syntax.
        offset_match = re.search(
            r"\s+LIMIT\s+(\d+)\s+OFFSET\s+(\d+)\s*;?\s*$",
            sql_query,
            re.IGNORECASE,
        )

        if offset_match:
            limit_value = int(offset_match.group(1))
            offset_value = int(offset_match.group(2))

            sql_query = re.sub(
                r"\s+LIMIT\s+\d+\s+OFFSET\s+\d+\s*;?\s*$",
                "",
                sql_query,
                flags=re.IGNORECASE,
            ).strip()

            # SQL Server requires ORDER BY before OFFSET/FETCH.
            if re.search(r"\bORDER\s+BY\b", sql_query, re.IGNORECASE):
                sql_query = (
                    sql_query.rstrip(";")
                    + f" OFFSET {offset_value} ROWS"
                    + f" FETCH NEXT {limit_value} ROWS ONLY"
                )
            else:
                raise ValueError(
                    "Cannot apply OFFSET without ORDER BY in SQL Server."
                )

        else:
            # Handle a simple LIMIT n.
            limit_match = re.search(
                r"\s+LIMIT\s+(\d+)\s*;?\s*$",
                sql_query,
                re.IGNORECASE,
            )

            if limit_match:
                limit_value = limit_match.group(1)

                sql_query = re.sub(
                    r"\s+LIMIT\s+\d+\s*;?\s*$",
                    "",
                    sql_query,
                    flags=re.IGNORECASE,
                ).strip()

                sql_query = re.sub(
                    r"^\s*SELECT\s+",
                    f"SELECT TOP {limit_value} ",
                    sql_query,
                    count=1,
                    flags=re.IGNORECASE,
                )


        # Convert PostgreSQL-style standard deviation functions
        # to SQL Server equivalents
        sql_query = re.sub(
            r"\bSTDEV_POP\s*\(",
            "STDEVP(",
            sql_query,
            flags=re.IGNORECASE
        )

        sql_query = re.sub(
            r"\bSTDEV_SAMP\s*\(",
            "STDEV(",
            sql_query,
            flags=re.IGNORECASE
        )

        return sql_query